# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(771, 667)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/resources/icon/探测声音.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 771, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_open_project = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/resources/icon/文件夹 .ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_open_project.setIcon(icon1)
        self.action_open_project.setWhatsThis("")
        self.action_open_project.setObjectName("action_open_project")
        self.action_close_project = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/resources/icon/关闭文件夹.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_close_project.setIcon(icon2)
        self.action_close_project.setObjectName("action_close_project")
        self.action_close = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/resources/icon/关闭.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_close.setIcon(icon3)
        self.action_close.setObjectName("action_close")
        self.action_save = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/resources/icon/保存.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_save.setIcon(icon4)
        self.action_save.setObjectName("action_save")
        self.action_about = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/resources/icon/信息.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_about.setIcon(icon5)
        self.action_about.setObjectName("action_about")
        self.action_help = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/resources/icon/帮助.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_help.setIcon(icon6)
        self.action_help.setObjectName("action_help")
        self.menu.addAction(self.action_open_project)
        self.menu.addAction(self.action_close_project)
        self.menu.addSeparator()
        self.menu.addAction(self.action_save)
        self.menu.addSeparator()
        self.menu.addAction(self.action_close)
        self.menu_2.addAction(self.action_about)
        self.menu_2.addAction(self.action_help)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.action_close.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "语音增强-客户端"))
        MainWindow.setToolTip(_translate("MainWindow", "打开一个项目文件夹"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))
        self.action_open_project.setText(_translate("MainWindow", "打开项目"))
        self.action_close_project.setText(_translate("MainWindow", "关闭项目"))
        self.action_close.setText(_translate("MainWindow", "关闭"))
        self.action_save.setText(_translate("MainWindow", "保存"))
        self.action_about.setText(_translate("MainWindow", "关于"))
        self.action_help.setText(_translate("MainWindow", "帮助"))
import apprcc_rc
