# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/sound_recording_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(551, 447)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/resources/icon/语音.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Frame.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = MatplotlibWidget(Frame)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sound_recording_save_path_lineEdit = QtWidgets.QLineEdit(Frame)
        self.sound_recording_save_path_lineEdit.setObjectName("sound_recording_save_path_lineEdit")
        self.horizontalLayout.addWidget(self.sound_recording_save_path_lineEdit)
        self.sound_recording_save_path_pushButton = QtWidgets.QPushButton(Frame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/resources/icon/文件夹.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sound_recording_save_path_pushButton.setIcon(icon1)
        self.sound_recording_save_path_pushButton.setObjectName("sound_recording_save_path_pushButton")
        self.horizontalLayout.addWidget(self.sound_recording_save_path_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sound_recording_save_path_start_pushButton = QtWidgets.QPushButton(Frame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/resources/icon/运行.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sound_recording_save_path_start_pushButton.setIcon(icon2)
        self.sound_recording_save_path_start_pushButton.setObjectName("sound_recording_save_path_start_pushButton")
        self.horizontalLayout_3.addWidget(self.sound_recording_save_path_start_pushButton)
        self.sound_recording_save_path_end_pushButton = QtWidgets.QPushButton(Frame)
        self.sound_recording_save_path_end_pushButton.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/resources/icon/结束.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sound_recording_save_path_end_pushButton.setIcon(icon3)
        self.sound_recording_save_path_end_pushButton.setCheckable(False)
        self.sound_recording_save_path_end_pushButton.setObjectName("sound_recording_save_path_end_pushButton")
        self.horizontalLayout_3.addWidget(self.sound_recording_save_path_end_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "录音窗口"))
        self.label.setText(_translate("Frame", "<html><head/><body><p>设置语音文件</p><p>保存路径</p></body></html>"))
        self.sound_recording_save_path_pushButton.setText(_translate("Frame", "打开"))
        self.sound_recording_save_path_start_pushButton.setText(_translate("Frame", "开始"))
        self.sound_recording_save_path_end_pushButton.setText(_translate("Frame", "结束并保存文件"))
from core.MatplotlibWidget import MatplotlibWidget
import apprcc_rc
